package com.myspace.mitest;

import java.time.LocalDate;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("Birthday")
	private LocalDate birthday;

	public Person() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.time.LocalDate getBirthday() {
		return this.birthday;
	}

	public void setBirthday(java.time.LocalDate birthday) {
		this.birthday = birthday;
	}

	public Person(java.lang.String name, java.time.LocalDate birthday) {
		this.name = name;
		this.birthday = birthday;
	}

}